{% set name = "haversine" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/haversine-{{ version }}.tar.gz
  sha256: 1103d7e1f0f108c25b31b63452c54d9d6f29389a70de7dd75fd4b908329b6fcf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - haversine
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mapado/haversine
  summary: Calculate the distance between 2 points on Earth.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
