{% set version = "0.5.0" %}

package:
  name: haversine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/haversine/haversine-{{ version }}.tar.gz
  sha256: 29fbceec1fcf295040f495f685e52a23a9101515045bfa49c26e379c46030858

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - haversine

about:
  home: https://github.com/mapado/haversine
  license: MIT
  summary: Calculate the distance between 2 points on Earth

extra:
  recipe-maintainers:
    - ocefpaf
